
# Configuration for abstract generation

epochs: 20
eval_every: 1

encoder:
  name: bert

decoder:
  num_heads: 6
  model_dim: 768
  ff_dim: 512
  max_length: 500
  num_blocks: 6

optimizer:
  name: adam
  lr: 1.e-06
  weight_decay: 0.0001

scheduler:
  name: cosine
  warmup_epochs: 2

data:
  root: ../track2_data
  val_split: 0.2
  batch_size: 8
