
# Configuration for abstract generation

epochs: 50
eval_every: 1

encoder:
  name: bert-base-uncased

decoder:
  num_heads: 6
  model_dim: 768
  ff_dim: 512
  max_length: 200
  num_blocks: 6

optimizer:
  name: adam
  lr: 1.e-04
  weight_decay: 0.0001

scheduler:
  name: cosine
  warmup_epochs: 0

data:
  root: ../track2_data
  val_split: 0.2
  batch_size: 8
